version: '3.5'

services:

  vegeta:
    build: .
    image: flaviostutz/vegeta
    ports:
      - 8880:8880
    command: echo "GET https://www.yahoo.com" | vegeta attack -duration=30s -rate=5 -prom-enable=true > /dev/null 2>&1

  prometheus:
    image: flaviostutz/prometheus
    ports:
      - 9090:9090
    environment:
      - SCRAPE_INTERVAL=10s
      - SCRAPE_TIMEOUT=10s
      - STATIC_SCRAPE_TARGETS=vegeta@vegeta:8880

  grafana:
    image: flaviostutz/grafana:5.2.4
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=mypass

